param(
  [Parameter(Mandatory=$true)][string]$SourceRoot,
  [Parameter(Mandatory=$true)][string]$CandidateRoot,
  [Parameter(Mandatory=$false)][switch]$NoBrowser
)
$ErrorActionPreference="Stop"
$DbContainer="automation-platform-local-db";$DbName="automation_local";$DbUser="postgres";$LocalUrl="http://127.0.0.1:3000"
function Text-Sha256([string]$Text){$bytes=[Text.Encoding]::UTF8.GetBytes($Text);$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace("-","").ToLowerInvariant()}finally{$sha.Dispose()}}
function Sql-Literal([string]$Value){return "'" + $Value.Replace("'","''") + "'"}
function Verify-Package([string]$Root,[string]$Verifier){$raw=& node.exe $Verifier --root $Root --json;if($LASTEXITCODE-ne0){throw "PACKAGE_MANIFEST_VERIFICATION_FAILED:$Root"};$result=$raw|ConvertFrom-Json;if([string]$result.status-ne"PASS"){throw "PACKAGE_MANIFEST_VERIFICATION_FAILED:$Root"};return $result}
function Get-DbLedger(){
  $lines=@(& docker.exe exec $DbContainer psql -U $DbUser -d $DbName -Atqc "select version||'|'||checksum_sha256 from app_private.schema_migrations order by version asc;")
  if($LASTEXITCODE-ne0){throw "DATABASE_MIGRATION_LEDGER_UNAVAILABLE"};$clean=@($lines|ForEach-Object{$_.Trim()}|Where-Object{$_});$text=[string]::Join("`n",@($clean|ForEach-Object{$p=$_.Split('|',2);"$($p[0]):$($p[1])"}));return [ordered]@{count=$clean.Count;digest=Text-Sha256 $text;lines=$clean}
}
function Invoke-Db([string]$Sql){& docker.exe exec $DbContainer psql -U $DbUser -d $DbName -v ON_ERROR_STOP=1 -c $Sql *> $null;if($LASTEXITCODE-ne0){throw "DATABASE_AUDIT_WRITE_FAILED"}}
function Config-Digest([string]$Root,$Entries){$parts=@();foreach($entry in @($Entries)|Sort-Object path){$file=Join-Path $Root ([string]$entry.path);if(-not(Test-Path -LiteralPath $file)){throw "UPGRADE_CONFIG_DRIFT_MISSING:$($entry.path)"};$hash=(Get-FileHash -LiteralPath $file -Algorithm SHA256).Hash.ToLowerInvariant();$bytes=(Get-Item -LiteralPath $file).Length;if($hash-ne([string]$entry.sha256).ToLowerInvariant()-or$bytes-ne[int64]$entry.bytes){throw "UPGRADE_CONFIG_DRIFT:$($entry.path)"};$parts += "$($entry.path):$hash`:$bytes"};return Text-Sha256 ([string]::Join("`n",$parts))}
function Capture-Integrity([string]$Root){$oldContainer=$env:INTEGRITY_DOCKER_CONTAINER;$oldDb=$env:INTEGRITY_DB_NAME;$oldUser=$env:INTEGRITY_DB_USER;try{$env:INTEGRITY_DOCKER_CONTAINER=$DbContainer;$env:INTEGRITY_DB_NAME=$DbName;$env:INTEGRITY_DB_USER=$DbUser;$raw=& node.exe (Join-Path $Root "scripts\database-integrity-cli.mjs");if($LASTEXITCODE-ne0){throw "DATABASE_INTEGRITY_CAPTURE_FAILED"};return $raw|ConvertFrom-Json}finally{$env:INTEGRITY_DOCKER_CONTAINER=$oldContainer;$env:INTEGRITY_DB_NAME=$oldDb;$env:INTEGRITY_DB_USER=$oldUser}}
function Invoke-Stop([string]$Root){& powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File (Join-Path $Root "scripts\windows\Stop-Local-Runtime.ps1") -SourceRoot $Root -DrainTimeoutSeconds 120 -KeepDatabaseRunning;if($LASTEXITCODE-ne0){throw "RUNTIME_DRAIN_FAILED:$Root"}}
function Invoke-Start([string]$Root,[string]$Label){$runId="{0}-{1}" -f (Get-Date -Format "yyyyMMddHHmmssfff"),([Guid]::NewGuid().ToString("N").Substring(0,8));$work=Join-Path $Root "Relatorios-Atualizacao-Local\$Label-$runId";New-Item -ItemType Directory -Path $work -Force|Out-Null;$log=Join-Path $work "CONSOLE_OUTPUT.log";& powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File (Join-Path $Root "scripts\windows\Start-Local-Runtime.ps1") -SourceRoot $Root -WorkDir $work -ConsoleLog $log -NoBrowser;if($LASTEXITCODE-ne0){throw "RUNTIME_START_FAILED:$Root"};return $work}
function Write-JsonAtomic([string]$Path,$Value){$dir=[IO.Path]::GetDirectoryName($Path);New-Item -ItemType Directory -Path $dir -Force|Out-Null;$tmp="$Path.$PID.tmp";$Value|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $tmp -Encoding UTF8;Move-Item -LiteralPath $tmp -Destination $Path -Force}
function Write-Marker([string]$Path,$Value){Write-JsonAtomic $Path $Value}
$SourceRoot=[IO.Path]::GetFullPath($SourceRoot);$CandidateRoot=[IO.Path]::GetFullPath($CandidateRoot)
$planPath=Join-Path $CandidateRoot "UPGRADE_PLAN.json";$planShaPath=Join-Path $CandidateRoot "UPGRADE_PLAN.sha256";$historyDir=Join-Path $CandidateRoot "upgrade-history";$receiptPath=Join-Path $CandidateRoot "UPGRADE_RECEIPT.json";$receiptShaPath=Join-Path $CandidateRoot "UPGRADE_RECEIPT.sha256"
$sourceStopped=$false;$candidateStarted=$false;$plan=$null;$planSha="";$failureMessage="";$startedAt=Get-Date
try{
  if($SourceRoot.TrimEnd('\')-eq$CandidateRoot.TrimEnd('\')){throw "CANDIDATE_MUST_BE_A_DIFFERENT_DIRECTORY"}
  if(-not(Test-Path -LiteralPath $planPath)-or-not(Test-Path -LiteralPath $planShaPath)){throw "UPGRADE_PLAN_NOT_PREPARED"}
  $planSha=(Get-Content -LiteralPath $planShaPath -Raw).Trim().ToLowerInvariant();if($planSha-notmatch'^[0-9a-f]{64}$'){throw "UPGRADE_PLAN_SHA256_INVALID"};$actualPlanSha=(Get-FileHash -LiteralPath $planPath -Algorithm SHA256).Hash.ToLowerInvariant();if($actualPlanSha-ne$planSha){throw "UPGRADE_PLAN_TAMPERED"}
  $plan=Get-Content -LiteralPath $planPath -Raw|ConvertFrom-Json;if([int]$plan.schemaVersion-ne2-or[string]$plan.status-ne"READY_FOR_CUTOVER"){throw "UPGRADE_PLAN_VERSION_OR_STATE_INVALID"}
  if([IO.Path]::GetFullPath([string]$plan.sourceRoot).TrimEnd('\')-ne$SourceRoot.TrimEnd('\')){throw "UPGRADE_PLAN_SOURCE_MISMATCH"};if([IO.Path]::GetFullPath([string]$plan.targetRoot).TrimEnd('\')-ne$CandidateRoot.TrimEnd('\')){throw "UPGRADE_PLAN_TARGET_MISMATCH"}
  $verifier=Join-Path $SourceRoot "scripts\verify-build-manifest.mjs";$sourcePackage=Verify-Package $SourceRoot $verifier;$candidatePackage=Verify-Package $CandidateRoot $verifier
  if(([string]$sourcePackage.manifestSha256)-ne([string]$plan.sourcePackageManifestDigest)){throw "SOURCE_PACKAGE_CHANGED_AFTER_PREPARE"};if(([string]$candidatePackage.manifestSha256)-ne([string]$plan.targetPackageManifestDigest)){throw "CANDIDATE_PACKAGE_CHANGED_AFTER_PREPARE"}
  $sourceConfig=Config-Digest $SourceRoot $plan.preservedConfigFiles;$candidateConfig=Config-Digest $CandidateRoot $plan.preservedConfigFiles;if($sourceConfig-ne[string]$plan.configSnapshotDigest-or$candidateConfig-ne[string]$plan.configSnapshotDigest){throw "UPGRADE_CONFIG_DIGEST_MISMATCH"}
  $backup=[IO.Path]::GetFullPath([string]$plan.preUpgradeBackup);if(-not(Test-Path -LiteralPath $backup)){throw "PRE_UPGRADE_BACKUP_NOT_FOUND"};$backupMirror=[IO.Path]::GetFullPath([string]$plan.candidateBackupMirror);if(-not(Test-Path -LiteralPath $backupMirror)){throw "CANDIDATE_BACKUP_MIRROR_NOT_FOUND"};$backupSha=(Get-FileHash -LiteralPath $backup -Algorithm SHA256).Hash.ToLowerInvariant();if($backupSha-ne([string]$plan.preUpgradeBackupSha256).ToLowerInvariant()){throw "PRE_UPGRADE_BACKUP_CHANGED"};if(((Get-FileHash -LiteralPath $backupMirror -Algorithm SHA256).Hash.ToLowerInvariant())-ne$backupSha){throw "CANDIDATE_BACKUP_MIRROR_CHANGED"};$backupManifest=Get-Content -LiteralPath "$backup.json" -Raw|ConvertFrom-Json;if(([string]$backupManifest.integrityProfile.profileDigestSha256)-ne[string]$plan.sourceIntegrityDigest){throw "PRE_UPGRADE_BACKUP_INTEGRITY_CHANGED"}
  & docker.exe inspect $DbContainer *> $null;if($LASTEXITCODE-ne0){throw "LOCAL_DATABASE_NOT_FOUND"};& docker.exe start $DbContainer *> $null
  $dbBefore=Get-DbLedger;if($dbBefore.count-ne[int]$plan.databaseMigrationCount-or$dbBefore.digest-ne[string]$plan.databaseLedgerDigest){throw "DATABASE_CHANGED_AFTER_UPGRADE_PREPARE"}
  & (Join-Path $CandidateRoot "scripts\windows\Test-PowerShellSyntax.ps1") -DirectoryPath (Join-Path $CandidateRoot "scripts\windows");if($LASTEXITCODE-ne0){throw "CANDIDATE_POWERSHELL_SYNTAX_FAILED"}
  Push-Location $CandidateRoot;try{foreach($guard in @("scripts/production-hardening-check.mjs","scripts/automation-disaster-recovery-check.mjs","scripts/automation-upgrade-cutover-check.mjs","scripts/automation-updater-transaction-check.mjs")){& node.exe $guard;if($LASTEXITCODE-ne0){throw "CANDIDATE_GUARD_FAILED:$guard"}}}finally{Pop-Location}
  $id=[string]$plan.transactionId;$sql="insert into app_private.disaster_recovery_operations(id,operation_type,state,phase,backup_sha256,migration_ledger_digest,initiated_by,source_release,target_release,source_integrity_digest,config_snapshot_digest,rollback_strategy) values ("+(Sql-Literal $id)+"::uuid,'upgrade','validating','pre-cutover',"+(Sql-Literal $backupSha)+","+(Sql-Literal ([string]$plan.databaseLedgerDigest))+",'windows-local-updater',"+(Sql-Literal ([string]$plan.sourceBuild))+","+(Sql-Literal ([string]$plan.targetBuild))+","+(Sql-Literal ([string]$plan.sourceIntegrityDigest))+","+(Sql-Literal ([string]$plan.configSnapshotDigest))+","+(Sql-Literal ([string]$plan.rollbackStrategy))+") on conflict(id) do update set state='validating',phase='pre-cutover',updated_at=now();";Invoke-Db $sql
  Write-JsonAtomic (Join-Path $historyDir "$id.json") ([ordered]@{schemaVersion=1;transactionId=$id;state="validating";startedAt=$startedAt.ToString("o");sourceRoot=$SourceRoot;targetRoot=$CandidateRoot;planSha256=$planSha;backupSha256=$backupSha;rollbackStrategy=[string]$plan.rollbackStrategy})
  Invoke-Stop $SourceRoot;$sourceStopped=$true;Invoke-Db ("update app_private.disaster_recovery_operations set state='running',phase='candidate-start',updated_at=now() where id="+(Sql-Literal $id)+"::uuid;")
  $candidateWork=Invoke-Start $CandidateRoot "Cutover";$candidateStarted=$true
  $dbAfter=Get-DbLedger;$targetIntegrity=Capture-Integrity $CandidateRoot
  $receipt=[ordered]@{schemaVersion=1;status="COMPLETED";transactionId=$id;startedAt=$startedAt.ToString("o");completedAt=(Get-Date).ToString("o");sourceRoot=$SourceRoot;targetRoot=$CandidateRoot;sourceBuild=[string]$plan.sourceBuild;targetBuild=[string]$plan.targetBuild;sourcePackageManifestDigest=[string]$plan.sourcePackageManifestDigest;targetPackageManifestDigest=[string]$plan.targetPackageManifestDigest;upgradePlanSha256=$planSha;preUpgradeBackup=$backup;candidateBackupMirror=$backupMirror;preUpgradeBackupSha256=$backupSha;configSnapshotPath=[string]$plan.configSnapshotPath;configSnapshotDigest=[string]$plan.configSnapshotDigest;rollbackStrategy=[string]$plan.rollbackStrategy;preUpgradeMigrationCount=[int]$plan.databaseMigrationCount;preUpgradeLedgerDigest=[string]$plan.databaseLedgerDigest;postUpgradeMigrationCount=$dbAfter.count;postUpgradeLedgerDigest=$dbAfter.digest;sourceIntegrityDigest=[string]$plan.sourceIntegrityDigest;targetIntegrityDigest=[string]$targetIntegrity.profileDigestSha256;candidateRuntimeReport=$candidateWork;readinessVerified=$true}
  Write-JsonAtomic $receiptPath $receipt;$receiptSha=(Get-FileHash -LiteralPath $receiptPath -Algorithm SHA256).Hash.ToLowerInvariant();Set-Content -LiteralPath $receiptShaPath -Value $receiptSha -Encoding ASCII
  $complete="update app_private.disaster_recovery_operations set state='completed',phase='cutover-completed',updated_at=now(),completed_at=now(),cutover_verified_at=now(),target_integrity_digest="+(Sql-Literal ([string]$targetIntegrity.profileDigestSha256))+",upgrade_plan_digest="+(Sql-Literal $planSha)+",source_package_manifest_digest="+(Sql-Literal ([string]$plan.sourcePackageManifestDigest))+",target_package_manifest_digest="+(Sql-Literal ([string]$plan.targetPackageManifestDigest))+",pre_upgrade_backup_sha256="+(Sql-Literal $backupSha)+",cutover_receipt_sha256="+(Sql-Literal $receiptSha)+" where id="+(Sql-Literal $id)+"::uuid;";Invoke-Db $complete
  Write-Marker (Join-Path $SourceRoot "SUPERSEDED_BY.json") ([ordered]@{schemaVersion=1;status="SUPERSEDED";transactionId=$id;supersededAt=(Get-Date).ToString("o");targetBuild=[string]$plan.targetBuild;targetPackageManifestDigest=[string]$plan.targetPackageManifestDigest;targetRoot=$CandidateRoot})
  Write-Marker (Join-Path $CandidateRoot "ACTIVE_RELEASE.json") ([ordered]@{schemaVersion=1;status="ACTIVE";transactionId=$id;activatedAt=(Get-Date).ToString("o");sourceBuild=[string]$plan.sourceBuild;targetBuild=[string]$plan.targetBuild;receiptSha256=$receiptSha})
  Write-JsonAtomic (Join-Path $historyDir "$id.json") ([ordered]@{schemaVersion=1;transactionId=$id;state="completed";startedAt=$startedAt.ToString("o");completedAt=(Get-Date).ToString("o");planSha256=$planSha;receiptSha256=$receiptSha;rollbackStrategy=[string]$plan.rollbackStrategy})
  Write-Host "UPGRADE CUTOVER PASS" -ForegroundColor Green;Write-Host "Candidate ativo: $CandidateRoot";Write-Host "Receipt: $receiptPath";Write-Host "Rollback: REVERTER-ATUALIZACAO-WINDOWS.cmd"
  if(-not$NoBrowser){Start-Process "$LocalUrl/testing"|Out-Null};exit 0
}catch{
  $failureMessage=$_.Exception.Message;Write-Host "UPGRADE CUTOVER FAIL: $failureMessage" -ForegroundColor Red
  if(-not$sourceStopped){exit 1}
  $rollbackStarted=Get-Date;$rollbackError="";try{
    try{& powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File (Join-Path $CandidateRoot "scripts\windows\Stop-Local-Runtime.ps1") -SourceRoot $CandidateRoot -DrainTimeoutSeconds 30 -KeepDatabaseRunning *> $null}catch{}
    $current=Get-DbLedger;$restoreRequired=($current.count-ne[int]$plan.databaseMigrationCount-or$current.digest-ne[string]$plan.databaseLedgerDigest)
    $restoreReceipt=$null
    if($restoreRequired){$restoreReceipt=Join-Path $historyDir ("rollback-restore-{0}.json" -f [string]$plan.transactionId);& powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File (Join-Path $SourceRoot "scripts\windows\Restore-Local-Primary.ps1") -SourceRoot $SourceRoot -BackupFile ([string]$plan.preUpgradeBackup) -ExpectedSha256 ([string]$plan.preUpgradeBackupSha256) -ExpectedLedgerDigest ([string]$plan.databaseLedgerDigest) -ExpectedIntegrityDigest ([string]$plan.sourceIntegrityDigest) -ReceiptPath $restoreReceipt;if($LASTEXITCODE-ne0){throw "AUTOMATIC_ROLLBACK_RESTORE_FAILED"}}
    Remove-Item -LiteralPath (Join-Path $SourceRoot "SUPERSEDED_BY.json") -Force -ErrorAction SilentlyContinue;Remove-Item -LiteralPath (Join-Path $CandidateRoot "ACTIVE_RELEASE.json") -Force -ErrorAction SilentlyContinue
    $sourceWork=Invoke-Start $SourceRoot "Rollback"
    if($null-ne$plan){try{Invoke-Db ("update app_private.disaster_recovery_operations set state='failed',phase='rolled-back',updated_at=now(),failed_at=coalesce(failed_at,now()),error_code='UPGRADE_FAILED_ROLLBACK_PASS',rollback_verified_at=now() where id="+(Sql-Literal ([string]$plan.transactionId))+"::uuid and state not in ('completed','failed','aborted');")}catch{}}
    if($null-ne$plan){$rollbackTransactionId=[string]$plan.transactionId;$rollbackBackup=[string]$plan.preUpgradeBackup}else{$rollbackTransactionId="unknown";$rollbackBackup=$null}
    $rollbackReceipt=[ordered]@{schemaVersion=1;status="UPGRADE_FAILED_ROLLBACK_PASS";transactionId=$rollbackTransactionId;upgradeError=$failureMessage;rolledBackAt=(Get-Date).ToString("o");restoreRequired=$restoreRequired;preUpgradeBackup=$rollbackBackup;sourceRuntimeReport=$sourceWork;durationMs=[int]((Get-Date)-$rollbackStarted).TotalMilliseconds}
    Write-JsonAtomic $receiptPath $rollbackReceipt;Write-Host "ROLLBACK AUTOMATICO PASS - versao anterior reativada." -ForegroundColor Yellow;exit 20
  }catch{
    $rollbackError=$_.Exception.Message
    if($null-ne$plan){$failedTransactionId=[string]$plan.transactionId}else{$failedTransactionId="unknown"}
    $failed=[ordered]@{schemaVersion=1;status="ROLLBACK_FAILED";transactionId=$failedTransactionId;upgradeError=$failureMessage;rollbackError=$rollbackError;failedAt=(Get-Date).ToString("o");manualRecoveryRequired=$true}
    try{Write-JsonAtomic $receiptPath $failed}catch{}
    Write-Host "ROLLBACK AUTOMATICO FALHOU: $rollbackError" -ForegroundColor Red;Write-Host "Nao inicie pacotes manualmente ate revisar o backup pre-upgrade.";exit 21
  }
}
