param(
  [Parameter(Mandatory=$true)][string]$SourceRoot,
  [Parameter(Mandatory=$true)][string]$CandidateRoot
)
$ErrorActionPreference="Stop"
$DbContainer="automation-platform-local-db";$DbName="automation_local";$DbUser="postgres"
function Fail([string]$Message){Write-Host "UPGRADE PREP FAIL: $Message" -ForegroundColor Red;exit 1}
function Text-Sha256([string]$Text){$bytes=[Text.Encoding]::UTF8.GetBytes($Text);$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace("-","").ToLowerInvariant()}finally{$sha.Dispose()}}
function Package-Ledger([string]$Root){$rows=@();Get-ChildItem -LiteralPath (Join-Path $Root "database") -Filter "*.sql"|Where-Object{$_.Name-match'^\d{3}_[A-Za-z0-9_]+\.sql$'}|Sort-Object Name|ForEach-Object{$rows += [ordered]@{version=$_.Name;checksumSha256=(Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()}};return ,$rows}
function Ledger-Digest($Rows){return Text-Sha256 ([string]::Join("`n",@($Rows|ForEach-Object{"$($_.version):$($_.checksumSha256)"})))}
function Verify-Package([string]$Root,[string]$Verifier){$raw=& node.exe $Verifier --root $Root --json;if($LASTEXITCODE-ne0){Fail "PACKAGE_MANIFEST_VERIFICATION_FAILED:$Root"};try{$result=$raw|ConvertFrom-Json}catch{Fail "PACKAGE_MANIFEST_RESULT_INVALID:$Root"};if([string]$result.status-ne"PASS"){Fail "PACKAGE_MANIFEST_VERIFICATION_FAILED:$Root"};return $result}
$SourceRoot=[IO.Path]::GetFullPath($SourceRoot);$CandidateRoot=[IO.Path]::GetFullPath($CandidateRoot)
if($SourceRoot.TrimEnd('\')-eq$CandidateRoot.TrimEnd('\')){Fail "CANDIDATE_MUST_BE_A_DIFFERENT_DIRECTORY"}
foreach($required in @("package.json","database","BUILD_MANIFEST.sha256","scripts\production-hardening-check.mjs","scripts\automation-disaster-recovery-check.mjs","scripts\automation-upgrade-cutover-check.mjs","scripts\automation-updater-transaction-check.mjs","scripts\verify-build-manifest.mjs","scripts\windows\Apply-Local-Upgrade.ps1","scripts\windows\Rollback-Local-Upgrade.ps1","scripts\windows\Restore-Local-Primary.ps1")){if(-not(Test-Path -LiteralPath (Join-Path $CandidateRoot $required))){Fail "CANDIDATE_MISSING:$required"}}
if($null-eq(Get-Command node.exe -ErrorAction SilentlyContinue)){Fail "NODE_NOT_FOUND"};if($null-eq(Get-Command docker.exe -ErrorAction SilentlyContinue)){Fail "DOCKER_NOT_FOUND"}
$verifier=Join-Path $SourceRoot "scripts\verify-build-manifest.mjs";if(-not(Test-Path -LiteralPath $verifier)){Fail "SOURCE_MANIFEST_VERIFIER_MISSING"}
$sourcePackage=Verify-Package $SourceRoot $verifier;$candidatePackage=Verify-Package $CandidateRoot $verifier
& docker.exe inspect $DbContainer *> $null;if($LASTEXITCODE-ne0){Fail "LOCAL_DATABASE_NOT_FOUND"};& docker.exe start $DbContainer *> $null
$dbLines=@(& docker.exe exec $DbContainer psql -U $DbUser -d $DbName -Atqc "select version||'|'||checksum_sha256 from app_private.schema_migrations order by version asc;");if($LASTEXITCODE-ne0-or$dbLines.Count-eq0){Fail "DATABASE_MIGRATION_LEDGER_UNAVAILABLE"}
$dbRows=@();foreach($line in $dbLines){if([string]::IsNullOrWhiteSpace($line)){continue};$parts=$line.Trim().Split('|',2);$dbRows += [ordered]@{version=$parts[0];checksumSha256=$parts[1]}}
$candidateRows=Package-Ledger $CandidateRoot;if($dbRows.Count-gt$candidateRows.Count){Fail "DATABASE_SCHEMA_AHEAD_OF_CANDIDATE"};for($i=0;$i-lt$dbRows.Count;$i++){if($dbRows[$i].version-ne$candidateRows[$i].version){Fail "MIGRATION_HISTORY_GAP_OR_OUT_OF_ORDER"};if($dbRows[$i].checksumSha256-ne$candidateRows[$i].checksumSha256){Fail "MIGRATION_CHECKSUM_MISMATCH"}}
Push-Location $CandidateRoot
try{foreach($guard in @("scripts/production-hardening-check.mjs","scripts/automation-disaster-recovery-check.mjs","scripts/automation-upgrade-cutover-check.mjs","scripts/automation-updater-transaction-check.mjs")){& node.exe $guard;if($LASTEXITCODE-ne0){Fail "CANDIDATE_GUARD_FAILED:$guard"}}}finally{Pop-Location}
$before=Get-ChildItem -LiteralPath (Join-Path $SourceRoot "backups") -Filter "automation-platform-*.dump" -ErrorAction SilentlyContinue|Select-Object -ExpandProperty FullName
& (Join-Path $SourceRoot "scripts\windows\Backup-Local-Data.ps1") -SourceRoot $SourceRoot
if($LASTEXITCODE-ne0){Fail "PRE_UPGRADE_BACKUP_FAILED"}
$after=Get-ChildItem -LiteralPath (Join-Path $SourceRoot "backups") -Filter "automation-platform-*.dump" -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending
$backup=$after|Where-Object{$before-notcontains$_.FullName}|Select-Object -First 1;if($null-eq$backup){$backup=$after|Select-Object -First 1};if($null-eq$backup){Fail "PRE_UPGRADE_BACKUP_NOT_FOUND"}
$backupManifestPath="$($backup.FullName).json";if(-not(Test-Path -LiteralPath $backupManifestPath)){Fail "PRE_UPGRADE_BACKUP_MANIFEST_NOT_FOUND"};$backupManifest=Get-Content -LiteralPath $backupManifestPath -Raw|ConvertFrom-Json;if([int]$backupManifest.schemaVersion-lt4-or$null-eq$backupManifest.integrityProfile){Fail "PRE_UPGRADE_BACKUP_MANIFEST_INCOMPATIBLE"}
$backupSha=(Get-FileHash -LiteralPath $backup.FullName -Algorithm SHA256).Hash.ToLowerInvariant();if($backupSha-ne([string]$backupManifest.sha256).ToLowerInvariant()){Fail "PRE_UPGRADE_BACKUP_SHA256_MISMATCH"}
$stamp=Get-Date -Format "yyyyMMdd-HHmmssfff";$snapshotRoot=Join-Path $SourceRoot "upgrade-snapshots\$stamp";New-Item -ItemType Directory -Path $snapshotRoot -Force|Out-Null
$configEntries=@();foreach($relative in @(".env","apps\web\.env.local")){ $source=Join-Path $SourceRoot $relative;if(-not(Test-Path -LiteralPath $source)){continue};$dest=Join-Path $snapshotRoot $relative;New-Item -ItemType Directory -Path ([IO.Path]::GetDirectoryName($dest)) -Force|Out-Null;Copy-Item -LiteralPath $source -Destination $dest -Force;$hash=(Get-FileHash -LiteralPath $source -Algorithm SHA256).Hash.ToLowerInvariant();$configEntries += [ordered]@{path=$relative;sha256=$hash;bytes=(Get-Item $source).Length};$candidateDest=Join-Path $CandidateRoot $relative;if(Test-Path -LiteralPath $candidateDest){$candidateHash=(Get-FileHash -LiteralPath $candidateDest -Algorithm SHA256).Hash.ToLowerInvariant();if($candidateHash-ne$hash){Fail "UPGRADE_CONFIG_CONFLICT:$relative"}}else{New-Item -ItemType Directory -Path ([IO.Path]::GetDirectoryName($candidateDest)) -Force|Out-Null;Copy-Item -LiteralPath $source -Destination $candidateDest -Force}}
$configDigest=Text-Sha256 ([string]::Join("`n",@($configEntries|Sort-Object path|ForEach-Object{"$($_.path):$($_.sha256):$($_.bytes)"})))
$sourceBackups=Join-Path $SourceRoot "backups";$candidateBackups=Join-Path $CandidateRoot "backups";if(Test-Path -LiteralPath $sourceBackups){New-Item -ItemType Directory -Path $candidateBackups -Force|Out-Null;Copy-Item -Path (Join-Path $sourceBackups "*") -Destination $candidateBackups -Recurse -Force -ErrorAction Stop};$candidateBackupMirror=Join-Path $candidateBackups $backup.Name;if(-not(Test-Path -LiteralPath $candidateBackupMirror)){Fail "CANDIDATE_BACKUP_MIRROR_MISSING"};if(((Get-FileHash -LiteralPath $candidateBackupMirror -Algorithm SHA256).Hash.ToLowerInvariant())-ne$backupSha){Fail "CANDIDATE_BACKUP_MIRROR_HASH_MISMATCH"}
$sourceBuild=if(Test-Path(Join-Path $SourceRoot "PACKAGE_BUILD.txt")){(Get-Content(Join-Path $SourceRoot "PACKAGE_BUILD.txt") -Raw).Trim()}else{"unknown"};$targetBuild=if(Test-Path(Join-Path $CandidateRoot "PACKAGE_BUILD.txt")){(Get-Content(Join-Path $CandidateRoot "PACKAGE_BUILD.txt") -Raw).Trim()}else{"unknown"}
$rollbackStrategy=if($candidateRows.Count-gt$dbRows.Count){"restore-backup"}else{"schema-compatible"}
$transactionId=[Guid]::NewGuid().ToString();$plan=[ordered]@{schemaVersion=2;status="READY_FOR_CUTOVER";transactionId=$transactionId;createdAt=(Get-Date).ToString("o");sourceRoot=$SourceRoot;targetRoot=$CandidateRoot;sourceBuild=$sourceBuild;targetBuild=$targetBuild;sourcePackageManifestDigest=[string]$sourcePackage.manifestSha256;sourcePackageManifestEntries=[int]$sourcePackage.entries;targetPackageManifestDigest=[string]$candidatePackage.manifestSha256;targetPackageManifestEntries=[int]$candidatePackage.entries;databaseMigrationCount=$dbRows.Count;candidateMigrationCount=$candidateRows.Count;databaseLedgerDigest=(Ledger-Digest $dbRows);candidateLedgerDigest=(Ledger-Digest $candidateRows);pendingMigrations=@($candidateRows|Select-Object -Skip $dbRows.Count|ForEach-Object{$_.version});preUpgradeBackup=$backup.FullName;candidateBackupMirror=$candidateBackupMirror;preUpgradeBackupSha256=$backupSha;sourceIntegrityDigest=[string]$backupManifest.integrityProfile.profileDigestSha256;configSnapshotPath=$snapshotRoot;configSnapshotDigest=$configDigest;preservedConfigFiles=@($configEntries);databaseVolumePreserved=$true;rollbackStrategy=$rollbackStrategy;notes=@("Nenhuma migration foi aplicada por este preparador.","O aplicador RC14 revalida pacote, configuracao, backup e ledger imediatamente antes do cutover.","Se o candidato avancar o schema, retornar ao binario anterior exige restaurar o backup pre-upgrade.")}
$planPath=Join-Path $CandidateRoot "UPGRADE_PLAN.json";$plan|ConvertTo-Json -Depth 10|Set-Content -LiteralPath $planPath -Encoding UTF8
$planSha=(Get-FileHash -LiteralPath $planPath -Algorithm SHA256).Hash.ToLowerInvariant();Set-Content -LiteralPath (Join-Path $CandidateRoot "UPGRADE_PLAN.sha256") -Value $planSha -Encoding ASCII
Write-Host "UPGRADE PREP PASS" -ForegroundColor Green;Write-Host "Transaction: $transactionId";Write-Host "Candidate: $CandidateRoot";Write-Host "Backup: $($backup.FullName)";Write-Host "Config snapshot: $snapshotRoot";Write-Host "Plan: $planPath";Write-Host "Plan SHA-256: $planSha";Write-Host "Rollback: $($plan.rollbackStrategy)"
