param(
  [Parameter(Mandatory=$true)][string]$CurrentRoot,
  [Parameter(Mandatory=$true)][string]$PreviousRoot,
  [Parameter(Mandatory=$false)][switch]$NoBrowser
)
$ErrorActionPreference="Stop"
$DbContainer="automation-platform-local-db";$DbName="automation_local";$DbUser="postgres";$LocalUrl="http://127.0.0.1:3000"
function Text-Sha256([string]$Text){$bytes=[Text.Encoding]::UTF8.GetBytes($Text);$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace("-","").ToLowerInvariant()}finally{$sha.Dispose()}}
function Verify-Package([string]$Root,[string]$Verifier){$raw=& node.exe $Verifier --root $Root --json;if($LASTEXITCODE-ne0){throw "PACKAGE_MANIFEST_VERIFICATION_FAILED:$Root"};$result=$raw|ConvertFrom-Json;if([string]$result.status-ne"PASS"){throw "PACKAGE_MANIFEST_VERIFICATION_FAILED:$Root"};return $result}
function Get-DbLedger(){ $lines=@(& docker.exe exec $DbContainer psql -U $DbUser -d $DbName -Atqc "select version||'|'||checksum_sha256 from app_private.schema_migrations order by version asc;");if($LASTEXITCODE-ne0){throw "DATABASE_MIGRATION_LEDGER_UNAVAILABLE"};$clean=@($lines|ForEach-Object{$_.Trim()}|Where-Object{$_});$text=[string]::Join("`n",@($clean|ForEach-Object{$p=$_.Split('|',2);"$($p[0]):$($p[1])"}));return [ordered]@{count=$clean.Count;digest=Text-Sha256 $text}}
function Config-Digest([string]$Root,$SnapshotRoot){$entries=@();foreach($relative in @(".env","apps\web\.env.local")){ $file=Join-Path $Root $relative;if(-not(Test-Path -LiteralPath $file)){continue};$entries += [ordered]@{path=$relative;sha256=(Get-FileHash -LiteralPath $file -Algorithm SHA256).Hash.ToLowerInvariant();bytes=(Get-Item -LiteralPath $file).Length}};$parts=@($entries|Sort-Object path|ForEach-Object{"$($_.path):$($_.sha256):$($_.bytes)"});return [ordered]@{digest=Text-Sha256 ([string]::Join("`n",$parts));entries=$entries}}
function Invoke-Stop([string]$Root){& powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File (Join-Path $Root "scripts\windows\Stop-Local-Runtime.ps1") -SourceRoot $Root -DrainTimeoutSeconds 120 -KeepDatabaseRunning;if($LASTEXITCODE-ne0){throw "RUNTIME_DRAIN_FAILED:$Root"}}
function Invoke-Start([string]$Root){$runId="{0}-{1}" -f (Get-Date -Format "yyyyMMddHHmmssfff"),([Guid]::NewGuid().ToString("N").Substring(0,8));$work=Join-Path $Root "Relatorios-Atualizacao-Local\Rollback-$runId";New-Item -ItemType Directory -Path $work -Force|Out-Null;$log=Join-Path $work "CONSOLE_OUTPUT.log";& powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File (Join-Path $Root "scripts\windows\Start-Local-Runtime.ps1") -SourceRoot $Root -WorkDir $work -ConsoleLog $log -NoBrowser;if($LASTEXITCODE-ne0){throw "PREVIOUS_RUNTIME_START_FAILED"};return $work}
function Write-JsonAtomic([string]$Path,$Value){$dir=[IO.Path]::GetDirectoryName($Path);New-Item -ItemType Directory -Path $dir -Force|Out-Null;$tmp="$Path.$PID.tmp";$Value|ConvertTo-Json -Depth 10|Set-Content -LiteralPath $tmp -Encoding UTF8;Move-Item -LiteralPath $tmp -Destination $Path -Force}
$CurrentRoot=[IO.Path]::GetFullPath($CurrentRoot);$PreviousRoot=[IO.Path]::GetFullPath($PreviousRoot);$receiptPath=Join-Path $CurrentRoot "UPGRADE_RECEIPT.json";$rollbackFailureReceipt=Join-Path $CurrentRoot "ROLLBACK_RECEIPT.json"
try{
  $receiptPath=Join-Path $CurrentRoot "UPGRADE_RECEIPT.json";if(-not(Test-Path -LiteralPath $receiptPath)){throw "UPGRADE_RECEIPT_NOT_FOUND"};$receipt=Get-Content -LiteralPath $receiptPath -Raw|ConvertFrom-Json;if([string]$receipt.status-ne"COMPLETED"){throw "UPGRADE_RECEIPT_NOT_COMPLETED"}
$receiptShaPath=Join-Path $CurrentRoot "UPGRADE_RECEIPT.sha256";if(-not(Test-Path -LiteralPath $receiptShaPath)){throw "UPGRADE_RECEIPT_SHA256_NOT_FOUND"};$expectedReceiptSha=(Get-Content -LiteralPath $receiptShaPath -Raw).Trim().ToLowerInvariant();$actualReceiptSha=(Get-FileHash -LiteralPath $receiptPath -Algorithm SHA256).Hash.ToLowerInvariant();if($actualReceiptSha-ne$expectedReceiptSha){throw "UPGRADE_RECEIPT_TAMPERED"}
$verifier=Join-Path $CurrentRoot "scripts\verify-build-manifest.mjs";$currentPackage=Verify-Package $CurrentRoot $verifier;$previousPackage=Verify-Package $PreviousRoot $verifier;if(([string]$currentPackage.manifestSha256)-ne[string]$receipt.targetPackageManifestDigest){throw "CURRENT_PACKAGE_DOES_NOT_MATCH_RECEIPT"};if(([string]$previousPackage.manifestSha256)-ne[string]$receipt.sourcePackageManifestDigest){throw "PREVIOUS_PACKAGE_DOES_NOT_MATCH_RECEIPT"}
$config=Config-Digest $CurrentRoot ([string]$receipt.configSnapshotPath);if($config.digest-ne[string]$receipt.configSnapshotDigest){throw "ROLLBACK_CONFIG_DRIFT_DETECTED"}
foreach($entry in @($config.entries)){ $dest=Join-Path $PreviousRoot ([string]$entry.path);if(Test-Path -LiteralPath $dest){$hash=(Get-FileHash -LiteralPath $dest -Algorithm SHA256).Hash.ToLowerInvariant();if($hash-ne[string]$entry.sha256){throw "PREVIOUS_PACKAGE_CONFIG_CONFLICT:$($entry.path)"}}else{New-Item -ItemType Directory -Path ([IO.Path]::GetDirectoryName($dest)) -Force|Out-Null;Copy-Item -LiteralPath (Join-Path $CurrentRoot ([string]$entry.path)) -Destination $dest -Force}}
$backup=$null;foreach($candidateBackup in @([string]$receipt.preUpgradeBackup,[string]$receipt.candidateBackupMirror)){if([string]::IsNullOrWhiteSpace($candidateBackup)){continue};$full=[IO.Path]::GetFullPath($candidateBackup);if(Test-Path -LiteralPath $full){$candidateSha=(Get-FileHash -LiteralPath $full -Algorithm SHA256).Hash.ToLowerInvariant();if($candidateSha-eq([string]$receipt.preUpgradeBackupSha256).ToLowerInvariant()){$backup=$full;break}}};if($null-eq$backup){throw "ROLLBACK_BACKUP_NOT_FOUND_OR_HASH_MISMATCH"};$sha=(Get-FileHash -LiteralPath $backup -Algorithm SHA256).Hash.ToLowerInvariant()
& docker.exe inspect $DbContainer *> $null;if($LASTEXITCODE-ne0){throw "LOCAL_DATABASE_NOT_FOUND"};& docker.exe start $DbContainer *> $null
$started=Get-Date;Invoke-Stop $CurrentRoot
$currentLedger=Get-DbLedger;$restoreRequired=([string]$receipt.rollbackStrategy-eq"restore-backup")-or($currentLedger.digest-ne[string]$receipt.preUpgradeLedgerDigest)-or($currentLedger.count-ne[int]$receipt.preUpgradeMigrationCount)
$restoreReceipt=$null
if($restoreRequired){$restoreReceipt=Join-Path $CurrentRoot "upgrade-history\manual-rollback-restore-$([string]$receipt.transactionId).json";& powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PreviousRoot "scripts\windows\Restore-Local-Primary.ps1") -SourceRoot $PreviousRoot -BackupFile $backup -ExpectedSha256 ([string]$receipt.preUpgradeBackupSha256) -ExpectedLedgerDigest ([string]$receipt.preUpgradeLedgerDigest) -ExpectedIntegrityDigest ([string]$receipt.sourceIntegrityDigest) -ReceiptPath $restoreReceipt;if($LASTEXITCODE-ne0){throw "MANUAL_ROLLBACK_RESTORE_FAILED"}}
Remove-Item -LiteralPath (Join-Path $PreviousRoot "SUPERSEDED_BY.json") -Force -ErrorAction SilentlyContinue;Remove-Item -LiteralPath (Join-Path $CurrentRoot "ACTIVE_RELEASE.json") -Force -ErrorAction SilentlyContinue
$work=Invoke-Start $PreviousRoot
$rollbackReceipt=[ordered]@{schemaVersion=1;status="ROLLBACK_COMPLETED";transactionId=[string]$receipt.transactionId;rolledBackAt=(Get-Date).ToString("o");currentRoot=$CurrentRoot;previousRoot=$PreviousRoot;currentBuild=[string]$receipt.targetBuild;restoredBuild=[string]$receipt.sourceBuild;restoreRequired=$restoreRequired;backupFile=$backup;backupSha256=[string]$receipt.preUpgradeBackupSha256;previousRuntimeReport=$work;durationMs=[int]((Get-Date)-$started).TotalMilliseconds}
$rollbackPath=Join-Path $CurrentRoot "ROLLBACK_RECEIPT.json";Write-JsonAtomic $rollbackPath $rollbackReceipt;Copy-Item -LiteralPath $rollbackPath -Destination (Join-Path $PreviousRoot "ROLLBACK_RECEIPT.json") -Force
Write-JsonAtomic (Join-Path $CurrentRoot "ROLLED_BACK_TO.json") ([ordered]@{schemaVersion=1;status="ROLLED_BACK";transactionId=[string]$receipt.transactionId;rolledBackAt=(Get-Date).ToString("o");previousRoot=$PreviousRoot;previousBuild=[string]$receipt.sourceBuild})
Write-JsonAtomic (Join-Path $PreviousRoot "ACTIVE_RELEASE.json") ([ordered]@{schemaVersion=1;status="ACTIVE_AFTER_ROLLBACK";transactionId=[string]$receipt.transactionId;activatedAt=(Get-Date).ToString("o");sourceBuild=[string]$receipt.targetBuild;targetBuild=[string]$receipt.sourceBuild})
Write-Host "ROLLBACK PASS" -ForegroundColor Green;Write-Host "Versao restaurada: $PreviousRoot";Write-Host "Receipt: $rollbackPath";if(-not$NoBrowser){Start-Process "$LocalUrl/testing"|Out-Null};exit 0
}catch{
  $rollbackError=$_.Exception.Message
  $failed=[ordered]@{schemaVersion=1;status="ROLLBACK_FAILED";failedAt=(Get-Date).ToString("o");currentRoot=$CurrentRoot;previousRoot=$PreviousRoot;error=$rollbackError;manualRecoveryRequired=$true}
  try{Write-JsonAtomic $rollbackFailureReceipt $failed}catch{}
  Write-Host "ROLLBACK FAIL: $rollbackError" -ForegroundColor Red
  Write-Host "Revise o backup pre-upgrade e o receipt antes de qualquer acao manual." -ForegroundColor Yellow
  exit 21
}
