import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.117.2";
import postgres from "npm:postgres@3.4.9";

const TOKEN_NAME = "meta_webhook_verify_token";
const TOKEN_DESCRIPTION = "Instagram webhook verification token generated by G3 Console";
const WEBHOOK_URL = "https://cqtrigqlktekczbbsxiy.supabase.co/functions/v1/instagram-webhook";

interface MembershipRow {
  workspace_id: string;
  role: string;
}

Deno.serve(async (request: Request) => {
  const cors = corsHeaders(request);

  if (request.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: cors });
  }
  if (request.method !== "POST") {
    return json({ error: "method_not_allowed" }, 405, cors, { allow: "POST, OPTIONS" });
  }
  if (!originAllowed(request)) {
    return json({ error: "origin_not_allowed" }, 403, cors);
  }

  const authorization = request.headers.get("authorization");
  if (!authorization?.startsWith("Bearer ")) {
    return json({ error: "authentication_required" }, 401, cors);
  }

  const supabaseUrl = Deno.env.get("SUPABASE_URL")?.trim();
  const publishableKey = defaultPublishableKey();
  const databaseUrl = Deno.env.get("SUPABASE_DB_URL")?.trim();
  if (!supabaseUrl || !publishableKey || !databaseUrl) {
    return json({ error: "runtime_not_configured" }, 503, cors);
  }

  const token = authorization.slice("Bearer ".length).trim();
  const authClient = createClient(supabaseUrl, publishableKey, {
    global: { headers: { Authorization: authorization } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
  const { data, error } = await authClient.auth.getUser(token);
  if (error || !data.user) {
    return json({ error: "authentication_invalid" }, 401, cors);
  }

  const sql = postgres(databaseUrl, {
    max: 1,
    prepare: false,
    idle_timeout: 5,
    connect_timeout: 10
  });

  try {
    const [membership] = await sql<MembershipRow[]>`
      select workspace_id, role
      from app_private.workspace_members
      where user_id = ${data.user.id}
      order by created_at asc, workspace_id asc
      limit 1
    `;

    if (!membership) return json({ error: "workspace_membership_required" }, 403, cors);
    if (membership.role !== "owner" && membership.role !== "admin") {
      return json({ error: "admin_role_required" }, 403, cors);
    }

    const verifyToken = randomToken();

    await sql.begin(async (tx) => {
      const [existing] = await tx<{ id: string }[]>`
        select id::text as id
        from vault.secrets
        where name = ${TOKEN_NAME}
        order by created_at desc
        limit 1
        for update
      `;

      if (existing) {
        await tx`
          select vault.update_secret(
            ${existing.id}::uuid,
            ${verifyToken},
            ${TOKEN_NAME},
            ${TOKEN_DESCRIPTION},
            null::uuid
          )
        `;
      } else {
        await tx`
          select vault.create_secret(
            ${verifyToken},
            ${TOKEN_NAME},
            ${TOKEN_DESCRIPTION},
            null::uuid
          )
        `;
      }

      await tx`
        insert into app_private.audit_logs (
          workspace_id,
          actor_user_id,
          action,
          resource_type,
          resource_id,
          metadata
        ) values (
          ${membership.workspace_id},
          ${data.user.id},
          'instagram.webhook.verify_token.rotated',
          'platform_secret',
          ${TOKEN_NAME},
          ${tx.json({
            source: "g3-webhook-token",
            returnedOnce: true,
            tokenBytes: 32
          })}
        )
      `;
    });

    return json({
      verifyToken,
      webhookCallback: WEBHOOK_URL,
      instruction: "Copy this verify token into the Meta webhook setup. It will not be shown again by this endpoint."
    }, 200, cors);
  } catch (error) {
    console.error("g3-webhook-token failed", safeErrorCode(error));
    return json({ error: "webhook_token_rotation_failed" }, 503, cors);
  } finally {
    await sql.end({ timeout: 1 });
  }
});

function randomToken(): string {
  const bytes = crypto.getRandomValues(new Uint8Array(32));
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary)
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/g, "");
}

function defaultPublishableKey(): string | null {
  const raw = Deno.env.get("SUPABASE_PUBLISHABLE_KEYS");
  if (raw) {
    try {
      const parsed = JSON.parse(raw) as Record<string, unknown>;
      const value = parsed.default;
      if (typeof value === "string" && value) return value;
    } catch {
      // Fall through while hosted projects still expose the legacy public key.
    }
  }
  return Deno.env.get("SUPABASE_ANON_KEY") ?? null;
}

function originAllowed(request: Request): boolean {
  const origin = request.headers.get("origin");
  if (!origin) return true;
  try {
    const url = new URL(origin);
    return url.protocol === "http:"
      && (url.hostname === "localhost" || url.hostname === "127.0.0.1" || url.hostname === "::1");
  } catch {
    return false;
  }
}

function corsHeaders(request: Request): HeadersInit {
  const origin = request.headers.get("origin");
  const allowed = origin && originAllowed(request) ? origin : "null";
  return {
    "access-control-allow-origin": allowed,
    "access-control-allow-methods": "POST, OPTIONS",
    "access-control-allow-headers": "authorization, apikey, content-type",
    "cache-control": "no-store",
    "vary": "origin"
  };
}

function json(
  body: unknown,
  status: number,
  headers: HeadersInit,
  extraHeaders: HeadersInit = {}
): Response {
  return Response.json(body, {
    status,
    headers: {
      ...headers,
      ...extraHeaders,
      "content-type": "application/json; charset=utf-8",
      "x-content-type-options": "nosniff",
      "referrer-policy": "no-referrer"
    }
  });
}

function safeErrorCode(error: unknown): string {
  if (!(error instanceof Error)) return "UNKNOWN_ERROR";
  const normalized = error.message
    .toUpperCase()
    .replace(/[^A-Z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return normalized.slice(0, 120) || "UNKNOWN_ERROR";
}
